version: '3.9'
services:
  imgproxy:
    image: darthsim/imgproxy:v3
    env_file:
      - .env
    container_name: ${APP_NAME}_imgproxy
    ports:
      - 8080:8080
    volumes:
      - ./media:/media
    restart: on-failure

  client:
    env_file:
      - .env
    container_name: ${APP_NAME}_client
    build: client
    ports:
      - 5173:5173
    restart: on-failure